config/routes.rb
Imgserv::Application.routes.draw do

devise_for :users

root :to => "home#index"

resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :imgdir, :uploadtime, :user_id
  belongs_to :users
  mount_uploader :imgdir, ImageUploader
  attr_accessor :embed_text, :embed_color, :embed_size, :embed_coords
  attr_accessible :embed_text, :embed_color, :embed_size, :embed_coords
  before_save :reset_embed_text, :if => :require_embed_text?
  
  def reset_embed_text
  	self.imgdir.recreate_versions!
  end
  
  def require_embed_text?
  	!embed_text.blank? and !embed_coords.blank?
  end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable, 
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :photos, :dependent => :destroy
  
  def valid_password?(password)
  	return false if encrypted_password.blank?
    if encrypted_password.length > 32
      bcrypt   = ::BCrypt::Password.new(encrypted_password)
      password = ::BCrypt::Engine.hash_secret("#{password}#{self.class.pepper}", bcrypt.salt)
      Devise.secure_compare(password, encrypted_password)
    else
      Devise.secure_compare(Digest::MD5.hexdigest(password), self.encrypted_password)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@images = Photo.find(:all, :limit => "255", :order => "RAND()")
		if user_signed_in?
			redirect_to :controller => "photos", :action => "new"
		end
	end
	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user!
	
	def new
		
		uid = current_user.id
		
		@photos = Photo.new
		
		#binding.pry
		@images = Photo.find(:all, :conditions => {:user_id => uid})
	end

	def create
		uid = current_user.id
		
		if current_user.photos.size >= 6
			redirect_to :action => 'new'
		else
			@p = Photo.new(:user_id => uid)
			@p.imgdir = params[:photo][:file]
		
			if @p.save!
			   redirect_to :action => 'new'
		  else
			   redirect_to :action => 'new'
		  end
    end
	end
	
	def destroy
		@img = Photo.find(params[:id])
		@img.destroy
		
		if @img.save!
			redirect_to :action => "new"
		end
	end
	
	def edit
		@photo = Photo.find(params[:id])
	end
	
	def update
		@photo = Photo.find(params[:id])
		#binding.pry
		if @photo.update_attributes(params[:photo])
			@photo.save!
			redirect_to :action => 'new'
		else
			render :edit
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def resourse_name
		:user
	end
	
	def resource
		@resource ||= User.new
	end
	
	def devise_mapping
		@devise_mapping ||= Devise.mapping[:user]
	end
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/home/index.html.erb
<div class="page-header">
	<h1>欢迎来到Stage1st</br><small>图片标注服务</small></h1>
</div>

<div class="container">
	<div class="row-fluid">
		<div class="span9">
			<% @images.each do |image| %>
				<li class="home">
					<%=link_to image_tag(image.imgdir.url(:embed), :height => "200", :width => "200"), image.imgdir.url(:embed), :class => "fancybox", :rel => "gp" if image.imgdir? %>
				</li>
			<% end %>
		</div>
			<div class="span3 pull-right">
				<h2>登陆</h2>
			<div class="form-inputs">
				<%= simple_form_for "user", :url => user_session_path do |f| %>
				<%= f.input :username, placeholder: 'S1用户名', :label => "用户名" %>
				<%= f.input :password, placeholder: '登陆密码', :label => "登陆密码" %>
					<div class="control-group boolean inline optional">
						<%= f.check_box :remember_me %> 记住我？
					</div>
					<div class="form-action">
					<%= f.submit "登陆", class: "btn btn-primary"%>
				</div>
				<p><%= link_to "忘记密码？", new_password_path('user') %></p>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imgserv</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar navbar-inner">
    <div class="container">
      <a class="brand" href="/">Imgserv: Stage1st图片标注服务</a>
    </div>
    <ul class="nav pull-right">
    <% if user_signed_in? %>
      登陆为 <%= current_user.email %>. 不是本人?
      <%= link_to "登出", destroy_user_session_path, :method => :delete %>
   <% else %>
     <%= link_to "注册", new_user_registration_path %> or
     <%= link_to "登陆", new_user_session_path %>
   <% end %>
    </ul>
  </div>
</div>

<div class="notice pull-right">
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
</div>

<div class="container">
  <%= yield %>
</div>

<div class="container">
<footer>
      <div class="container">
        <div class="nav pull-right">
        <a href="#" rel="external"><p>Powered by Stage1st</p></a>
        <p>Now:<%= Time.now %></p>
      </div>
      </div>
</footer>
</div>

</body>
</html>

app/views/photos/edit.html.erb
<div class='page-header'>
  <h1><center>请吐槽您上传的图片</center><h1>
</div>
<script type="text/javascript">
  $(document).ready(
    function()
    {
      $('#Expandable').jPicker(
        {
          window:
          {
            expandable: true
          }
        });
    });
  
  $(document).ready(
    function()
    {
      $('#imgcrop').Jcrop({
          onChange: showCoords,
          onSelect: showCoords
      });

    });

// Simple event handler, called from onChange and onSelect
// event handlers, as per the Jcrop invocation above
function showCoords(c)
{
//  alert('x='+ c.x +' y='+ c.y +' x2='+ c.x2 +' y2='+ x.y2)
//  alert('w='+c.w +' h='+ c.h)

    $('#coords').val(c.w + "," + c.h + "," + c.x + "," + c.y)

//  $('#x').val(c.x);
//  $('#y').val(c.y);
//  $('#x2').val(c.x2);
//  $('#y2').val(c.y2);
//  $('#w').val(c.w);
//  $('#h').val(c.h);
};

</script>


<div class="container">
  <div class="row-fluid">
    <div class="span7 offset1">
      <p>请吐槽您要吐槽的位置<p>
      <%= image_tag @photo.imgdir.url(:thumb), :label => "原图", :id => "imgcrop" if @photo.imgdir? %>
    </div>
<div class="span4 pull-right">
<%= simple_form_for @photo do |f| %>
  <%= f.input :embed_text, :label => "往这儿吐槽", :placeholder => "吐槽或者留空" %>
  <%= f.input :embed_size, :collection => 15..30, :label => "字体大小", :default => 15  %>
  <%= f.input :embed_color, :label => "选择颜色", :as => :hidden, :input_html => { :value => '000000', :id => 'Expandable' } %>
  <%= f.input :embed_coords, :as => :hidden, :input_html => {:id => "coords" } %>
  <%= f.submit "创建吐槽" %>
<% end %>
</div>
  </div>
</div>


<div class="span1 pull-right">
<%=link_to "返回前页",  new_photo_path %>
</div>

app/views/photos/new.html.erb
<div class="container">
   <div class="row-fluid">
    <div class="page-header">
	   <h1><center>您上传的图片(最多6张)</center></h1>
    </div>

<div class="span8">
 <% @images.each do |image| %>
      <li class="inner">
        <%=link_to image_tag(image.imgdir.url(:thumb)), image.imgdir.url if image.imgdir? %> 
        <%=link_to image_tag(image.imgdir.url(:embed)), image.imgdir.url(:embed), :class => "fancybox", :rel => "gpi" if !image.imgdir.embed.blank? %>

    <div class="btn-group">
      <%= link_to "吐槽", edit_photo_path(image), :class => "btn" %> 
      <%= link_to "删除", photo_path(image), :class => "btn", :confirm => '你确定要删除吗', :method => :delete %>
    </div>

      </li>

<% end %>
</div>

<div class="span3 pull-right">
  <div class="well">
    <h5>修正图片引用地址:<br>
    1 2 3<br>
    4 5 6<br>
    顺序上至下.</h3>
  <li class="url"> 
    <% @images.each do |img| %>
      <% if !img.imgdir.embed.blank? %>
            <h5><%= link_to "吐槽图片引用地址", img.imgdir.url(:embed) %></h5>
      <% else %>
            <h5>没有吐槽图片引用地址</h5>
    <% end %>
    <% end %>
  </li>
</div>

  
<%= simple_form_for @photos, :html => {:multipart => true} do |f| %>
	<h2><center><b>请上您的图片</b></h2>


<div class="fileupload fileupload-new" data-provides="fileupload">
  <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" /></div>
  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
  <div>
    <span class="btn btn-file"><span class="fileupload-new">选择图片</span><span class="fileupload-exists">改变当前图片</span><%= f.file_field :file %></span>
    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">取消</a>
    <span class="fileupload-exists"><%= f.submit "确定", :class => "btn btn-primary" %>
  </div>
</div>

<% end %>
</div>